# Jekyll Configuration for GitHub Pages
# Site settings
title: My Simple Website
email: your.email@example.com
description: >-
  A modern, responsive web experience built with clean code 
  and thoughtful design. Showcasing professional web development 
  skills and best practices.

# GitHub Pages settings
baseurl: "/my_simple_website"
url: "https://robotdingdong.github.io"

# Author information
author:
  name: Your Name
  email: your.email@example.com
  github: ROBOTdingDONG

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

# Jekyll Minifier settings
jekyll-minifier:
  uglifier_args:
    harmony: true
  compress_css: true
  compress_javascript: true
  compress_json: true
  simple_boolean_attribute: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  preserve_patterns:
    - "<!-- Google Analytics -->"
    - "<!-- End Google Analytics -->"

# Sass settings
sass:
  sass_dir: css
  style: compressed

# Exclude from processing
exclude:
  - .gitignore
  - .git/
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - "*.tmp"
  - "*.bak"

# Include files that start with underscore
include:
  - _pages
  - .htaccess
  - .nojekyll

# Collections (if you want to add blog posts later)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Permalink structure
permalink: pretty

# Pagination (if using blog)
paginate: 5
paginate_path: "/blog/page:num/"

# SEO settings
google_analytics: # Add your GA tracking ID here
twitter:
  username: # Your Twitter username
  card: summary_large_image

facebook:
  app_id: # Your Facebook App ID
  publisher: # Your Facebook Page URL

social:
  name: Your Name
  links:
    - https://github.com/ROBOTdingDONG
    - https://linkedin.com/in/yourprofile

# Site verification (add your verification codes)
google_site_verification: 
bing_site_verification:

# Timezone
timezone: America/New_York

# Language
lang: en

# Reading time calculation
reading_time: true

# Show excerpts on homepage
show_excerpts: true

# Date format
date_format: "%B %-d, %Y"

# Enable future posts
future: false

# Limit posts
limit_posts: 0

# Highlighter settings
rouge:
  default_lang: html
  css_class: 'highlight'
  span:
    line_numbers: false
  block:
    line_numbers: true
    start_line: 1

# Markdown settings
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  guess_lang: true
  footnote_nr: 1
